### ISSUE TITLE
Install into a bin

### ISSUE THREAD

**Issue by mfowlewebs** [boxen/puppet-gimp#2]
Please symlink the app into a bin directory; /opt/boxen/bin or some such. Ideally as 'gimp' rather than 'gimp-2.8'.

**Comment by jacobbednarz** [comment]
Deprecated in favour of [brewcask][1] and [Boxen's in built support for
homebrew/brewcask][2].

[1]: https://caskroom.github.io/
[2]: https://github.com/boxen/puppet-boxen/blob/master/manifests/personal.pp#L14-L17
